# Generated by Django 5.0.7 on 2024-08-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
